/-
Jinshi: the environment examinations (docs/jinshi.md). For the modules named, this walks the compiled environment and prints one JSON
line per finding:

  {"check": "tcb"|"shadow"|"arith"|"dossier"|"content", "severity": "fail"|"warn"|"info", "module": M, "name": N, "line": L, "detail": …}

and a last line {"check": "summary", …} with the counts. No Lean is elaborated here: everything is read from the environment the
modules were compiled into, as the merge queue's axiom check and the leak scan do.

  lake build tengoku-jinshi
  lake env .lake/build/bin/tengoku-jinshi --module Tengoku.Compfiles [--module …] [--import M …] [--seed Tengoku.Seed] [--check tcb,…]

`--seed` names the module prefix of the seed (what `shadow` compares a library's names against; the seed itself is exempt from
`arith` and `dossier`, which read a library's theorems). `--import` loads a module without examining it (the fixtures).
-/
import Lean
open Lean Meta

namespace Jinshi

structure Finding where
  check : String
  severity : String
  module : Name
  name : Name
  line : Option Nat := none
  detail : String

def Finding.json (f : Finding) : String :=
  (Json.mkObj [("check", f.check), ("severity", f.severity), ("module", f.module.toString), ("name", f.name.toString),
               ("line", match f.line with | some l => (l : Json) | none => Json.null), ("detail", f.detail)]).compress

/-- A declaration a reader may be told about: not internal, not generated by a macro, not one of the auxiliary families. -/
def okName (n : Name) : Bool :=
  !n.isInternal && !n.hasMacroScopes &&
    !(n.components.any fun c => match c with
      | .str _ s => s.startsWith "proof_" || s.startsWith "match_" || s.startsWith "eq_" || s.startsWith "_" || s == "injEq" || s.startsWith "sizeOf_"
      | _ => false)

structure Ctx where
  /-- the modules examined (indices into env.header.moduleNames) -/
  idxs : Array Nat
  /-- a module is examined when its name has one of these prefixes -/
  mods : List Name
  seed : Name
  checks : List String

def Ctx.on (c : Ctx) (check : String) : Bool := c.checks.isEmpty || c.checks.contains check

/-- the module of a constant, when it is one of the tree's -/
def moduleOf (env : Environment) (n : Name) : Option Name :=
  (env.getModuleIdxFor? n).bind fun i => env.header.moduleNames[i.toNat]?

def isSeedOrCore (c : Ctx) (env : Environment) (n : Name) : Bool :=
  match moduleOf env n with
  | some m => c.seed.isPrefixOf m || (`Init).isPrefixOf m || (`Lean).isPrefixOf m || (`Std).isPrefixOf m || (`Lake).isPrefixOf m
  | none => true  -- a constant of the prelude or of no module

def lineOf (n : Name) : CoreM (Option Nat) := do
  return (← findDeclarationRanges? n).map (·.range.pos.line)

/-- the constants of the examined modules, sorted by (module, name) so two runs give the same bytes -/
def selected (c : Ctx) (env : Environment) : Array (Name × Name × ConstantInfo) := Id.run do
  let mut out := #[]
  for (n, ci) in env.constants.toList do
    let some idx := env.getModuleIdxFor? n | continue
    unless c.idxs.contains idx.toNat do continue
    let some m := env.header.moduleNames[idx.toNat]? | continue
    out := out.push (m, n, ci)
  return out.qsort fun a b => a.1.toString < b.1.toString || (a.1 == b.1 && a.2.1.toString < b.2.1.toString)

/-! ## tcb — the trusted computing base of the round -/

def elabMonads : List Name := [`Lean.Elab, `Lean.Meta, `Lean.Core, `IO, `EIO, `BaseIO, `Lean.MacroM, `Lean.CommandElabM, `Lean.TermElabM]

def tcbKinds (env : Environment) (n : Name) (ci : ConstantInfo) : List String := Id.run do
  let mut ks := []
  if ci.isUnsafe then ks := ks ++ ["unsafe"]
  if let .axiomInfo _ := ci then ks := ks ++ ["axiom"]
  if let .opaqueInfo _ := ci then ks := ks ++ ["opaque"]
  if (Compiler.implementedByAttr.getParam? env n).isSome then ks := ks ++ ["implemented_by"]
  if isExtern env n then ks := ks ++ ["extern"]
  if (getInitFnNameFor? env n).isSome || isIOUnitInitFn env n then ks := ks ++ ["initialize"]
  let tyConsts := ci.type.getUsedConstants
  if tyConsts.any (fun k => elabMonads.any (·.isPrefixOf k)) then ks := ks ++ ["elaborator-code"]
  return ks

def tcb (c : Ctx) : CoreM (Array Finding) := do
  let env ← getEnv
  let mut out := #[]
  let mut tcbNames : NameSet := {}
  for (m, n, ci) in selected c env do
    let ks := tcbKinds env n ci
    unless ks.isEmpty do
      tcbNames := tcbNames.insert n
      if okName n then
        out := out.push { check := "tcb", severity := "info", module := m, name := n, line := ← lineOf n,
                          detail := s!"{", ".intercalate ks}: part of the trusted computing base" }
  -- a theorem whose STATEMENT mentions a TCB constant: what it says depends on code the kernel did not check
  for (m, n, ci) in selected c env do
    let .thmInfo _ := ci | continue
    unless okName n do continue
    let used := ci.type.getUsedConstants.filter fun k => tcbNames.contains k || (tcbKinds env k ((env.find? k).getD ci)).any (· != "elaborator-code")
    unless used.isEmpty do
      out := out.push { check := "tcb", severity := "warn", module := m, name := n, line := ← lineOf n,
                        detail := s!"statement mentions {used.toList}: {", ".intercalate ((used.toList.map fun k => tcbKinds env k ((env.find? k).getD ci)).flatten.eraseDups)}" }
  return out

/-! ## shadow — a library's names that are also the seed's -/

def suffixes (n : Name) : List Name :=
  let cs := n.components
  (List.range cs.length).drop 1 |>.map fun k => (cs.drop k).foldl (fun acc c => acc ++ c) Name.anonymous

def shadow (c : Ctx) : CoreM (Array Finding) := do
  let env ← getEnv
  let mut out := #[]
  let mut shadows : NameMap Name := {}
  for (m, n, ci) in selected c env do
    if c.seed.isPrefixOf m then continue
    unless okName n do continue
    if let .thmInfo _ := ci then continue  -- a theorem of the same name proves the same thing or fails to import; the gate's business
    for s in suffixes n do
      if let some sci := env.find? s then
        if isSeedOrCore c env s && okName s && !(sci matches .thmInfo _) then
          shadows := shadows.insert n s
          out := out.push { check := "shadow", severity := "warn", module := m, name := n, line := ← lineOf n,
                            detail := s!"declares `{n}` while the seed has `{s}` ({(moduleOf env s).getD `_}): a statement that `open`s the namespace reads as the seed's" }
          break
  -- the theorems that use a shadowing constant in their statement
  for (m, n, ci) in selected c env do
    let .thmInfo _ := ci | continue
    unless okName n do continue
    let used := ci.type.getUsedConstants.filter shadows.contains
    unless used.isEmpty do
      out := out.push { check := "shadow", severity := "warn", module := m, name := n, line := ← lineOf n,
                        detail := s!"statement uses {used.toList.map fun k => s!"{k} (not {(shadows.find? k).getD k})"}" }
  return out

/-! ## arith — defaulted numerals, truncated arithmetic, junk values, in a library's statements -/

def realLike : List Name := [`Real, `Complex, `Rat, `NNReal, `ENNReal, `EReal]

/-- the heads a junk-value or truncation finding names (plain names: this program imports only Lean, so none of them need exist) -/
def junkHeads : List (Name × String) :=
  [(`Real.sqrt, "Real.sqrt"), (`Real.log, "Real.log"), (`Real.rpow, "Real.rpow"), (`Real.arcsin, "Real.arcsin"), (`Real.arccos, "Real.arccos")]

partial def arithScan (e : Expr) (acc : Array String) : Array String :=
  let acc := match e.getAppFn.constName?, e.getAppArgs with
    | some ``HSub.hSub, #[.const ``Nat [], _, _, _, _, _] => acc.push "ℕ-subtraction"
    | some ``HDiv.hDiv, #[.const ``Nat [], _, _, _, _, _] => acc.push "ℕ-division"
    | some ``HDiv.hDiv, #[.const ``Int [], _, _, _, _, _] => acc.push "ℤ-division"
    | some ``HMod.hMod, #[.const ``Int [], _, _, _, _, _] => acc.push "ℤ-modulo"
    | some ``Inv.inv, #[.const t _, _, _] => if realLike.contains t then acc.push s!"{t}⁻¹" else acc
    | some ``HDiv.hDiv, #[.const t _, _, _, _, _, _] => if realLike.contains t then acc.push s!"{t}-division" else acc
    | some h, _ => match junkHeads.find? (·.1 == h) with
      | some (_, label) => acc.push label
      | none => acc
    | none, _ => acc
  match e with
  | .app f a => arithScan a (arithScan f acc)
  | .lam _ t b _ | .forallE _ t b _ => arithScan b (arithScan t acc)
  | .letE _ t v b _ => arithScan b (arithScan v (arithScan t acc))
  | .mdata _ b | .proj _ _ b => arithScan b acc
  | _ => acc

/-- a numeral `k ≥ 2` typed ℕ somewhere in the expression -/
partial def hasNatLit (e : Expr) : Bool :=
  (match e.getAppFn.constName?, e.getAppArgs with
   | some ``OfNat.ofNat, #[.const ``Nat [], .lit (.natVal k), _] => k ≥ 2
   | _, _ => false) ||
  (match e with
   | .app f a => hasNatLit f || hasNatLit a
   | .lam _ t b _ | .forallE _ t b _ => hasNatLit t || hasNatLit b
   | .letE _ t v b _ => hasNatLit t || hasNatLit v || hasNatLit b
   | .mdata _ b | .proj _ _ b => hasNatLit b
   | _ => false)

/-- numerals typed ℕ in a statement that also speaks of a real-like type: the classic `(1/2 : ℕ) = 0` -/
def natLiteralsNextToReals (e : Expr) : Bool :=
  e.getUsedConstants.any realLike.contains && hasNatLit e

def arith (c : Ctx) : CoreM (Array Finding) := do
  let env ← getEnv
  let mut out := #[]
  for (m, n, ci) in selected c env do
    if c.seed.isPrefixOf m then continue
    let .thmInfo _ := ci | continue
    unless okName n do continue
    let found := (arithScan ci.type #[]).toList.eraseDups
    let found := if natLiteralsNextToReals ci.type then found ++ ["ℕ-numeral next to a real-like type"] else found
    unless found.isEmpty do
      out := out.push { check := "arith", severity := "warn", module := m, name := n, line := ← lineOf n,
                        detail := s!"statement contains {", ".intercalate found}: check the hypotheses bound every argument (truncation and junk values make a weaker claim than the text reads)" }
  return out

/-! ## dossier — the library-local definitions a theorem's statement rests on -/

/-- `some reason` when a definition is not what a name would promise -/
def trivialDef (ci : ConstantInfo) : MetaM (Option String) := do
  let env ← getEnv
  match ci with
  | .defnInfo d =>
    lambdaTelescope d.value fun xs body => do
      let body ← instantiateMVars body
      if body.isConstOf ``True then return some "reduces to True"
      if body.isConstOf ``False then return some "reduces to False"
      let ty ← instantiateMVars (← inferType body)
      if ty.isProp && !xs.isEmpty && !xs.any (fun x => body.containsFVar x.fvarId!) then
        return some "a predicate that ignores every argument"
      return none
  | .inductInfo i =>
    if i.ctors.length == 1 && i.isRec == false then
      let some (.ctorInfo ctor) := env.find? i.ctors.head! | return none
      if ctor.numFields == 0 && i.numIndices == 0 then return some "a structure with no fields (every value is the same)"
    return none
  | _ => return none

def dossier (c : Ctx) : MetaM (Array Finding) := do
  let env ← getEnv
  let mut out := #[]
  let mut judged : NameMap (Option String) := {}
  for (m, n, ci) in selected c env do
    if c.seed.isPrefixOf m then continue
    let .thmInfo _ := ci | continue
    unless okName n do continue
    let locals := ci.type.getUsedConstants.filter fun k => !isSeedOrCore c env k && okName k && !(env.find? k matches some (.thmInfo _))
    if locals.isEmpty then continue
    let mut parts := #[]
    let mut bad := #[]
    for k in locals do
      let some kci := env.find? k | continue
      let verdict ← match judged.find? k with
        | some v => pure v
        | none => do
          let v ← try trivialDef kci catch _ => pure none
          judged := judged.insert k v
          pure v
      let shown ← try
          let s ← withOptions (fun o => pp.maxSteps.set (pp.proofs.set o false) 400) (ppExpr kci.type)
          pure (toString s)
        catch _ => pure "?"
      let shown := if shown.length > 160 then String.mk (shown.toList.take 160) ++ "…" else shown
      parts := parts.push s!"{k} : {shown.replace "\n" " "}"
      if let some why := verdict then bad := bad.push s!"{k}: {why}"
    out := out.push { check := "dossier", severity := if bad.isEmpty then "info" else "fail", module := m, name := n, line := ← lineOf n,
                      detail := (if bad.isEmpty then "" else s!"TRIVIAL {bad.toList} — ") ++ s!"rests on {locals.size} library definition(s): " ++ "; ".intercalate parts.toList }
  return out

/-! ## content — a theorem that says nothing -/

def content (c : Ctx) : MetaM (Array Finding) := do
  let env ← getEnv
  let mut out := #[]
  for (m, n, ci) in selected c env do
    let .thmInfo _ := ci | continue
    unless okName n do continue
    let why? ← try
        forallTelescope ci.type fun xs body => do
          let body ← instantiateMVars body
          if body.isConstOf ``True then return some "the conclusion is True"
          if let some (_, l, r) := body.eq? then
            if l == r then return some "the conclusion is `a = a`"
          if let some (l, r) := body.iff? then
            if l == r then return some "the conclusion is `p ↔ p`"
          for x in xs do
            if (← instantiateMVars (← inferType x)) == body then return some s!"the conclusion is the hypothesis `{← x.fvarId!.getUserName}`"
          return none
      catch _ => pure none
    if let some why := why? then
      out := out.push { check := "content", severity := "warn", module := m, name := n, line := ← lineOf n, detail := why }
  return out

end Jinshi

open Jinshi in
unsafe def main (argv : List String) : IO UInt32 := do
  enableInitializersExecution
  let opt (k : String) : List String := (argv.zip (argv.drop 1)).filterMap fun (a, b) => if a == k then some b else none
  let mods := (opt "--module").map String.toName
  let imports := (opt "--import").map String.toName ++ mods
  let seed := ((opt "--seed").headD "Tengoku.Seed").toName
  let checks := ((opt "--check").map fun s => (s.splitOn ",").map fun t => t.trimAscii.toString).flatten
  if imports.isEmpty then
    IO.eprintln "usage: tengoku-jinshi --module <M> [--module <M>…] [--import <M>…] [--seed <prefix>] [--check tcb,shadow,arith,dossier,content]"
    return 2
  initSearchPath (← findSysroot)
  let env ← importModules (imports.eraseDups.toArray.map fun m => { module := m }) {} (trustLevel := 0) (loadExts := true)
  let idxs := ((List.range env.header.moduleNames.size).filter fun i => mods.any (·.isPrefixOf env.header.moduleNames[i]!)).toArray
  let c : Ctx := { idxs, mods, seed, checks }
  let ctx : Core.Context := { fileName := "<tengoku-jinshi>", fileMap := default, maxHeartbeats := 0 }
  let run (x : MetaM (Array Finding)) : IO (Array Finding) := do
    let (r, _) ← (x.run' {} {}).toIO ctx { env }
    return r
  let mut all : Array Finding := #[]
  if c.on "tcb" then all := all ++ (← run (tcb c))
  if c.on "shadow" then all := all ++ (← run (shadow c))
  if c.on "arith" then all := all ++ (← run (arith c))
  if c.on "dossier" then all := all ++ (← run (dossier c))
  if c.on "content" then all := all ++ (← run (content c))
  for f in all do IO.println f.json
  let count (s : String) := (all.filter (·.severity == s)).size
  IO.println (Json.mkObj [("check", "summary"), ("modules", (idxs.size : Json)), ("findings", (all.size : Json)),
                          ("fail", (count "fail" : Json)), ("warn", (count "warn" : Json)), ("info", (count "info" : Json))]).compress
  return 0
