import Tengoku

/-!
# Exposure (Doob) martingale on a finite product sample

For a measurable space `Z`, an integer `n : ℕ`, and a real-valued
function `f : (Fin n → Z) → ℝ`, the *exposure martingale* (a.k.a. Doob
martingale of `f`) is the sequence

  `Mₖ S = E[f | ℱₖ] S`

where `ℱₖ` is the σ-algebra on `Fin n → Z` generated by the first `k`
coordinates of the sample, and the expectation is taken under a product
measure `μⁿ`. The exposure martingale telescopes between
`M₀ = E[f]` (a constant function) and `Mₙ = f` (a.e.), so its martingale
differences carry the entire deviation `f - E[f]`. This is the
construction the proof of McDiarmid's inequality builds on top of.

This module is **Stage B sub-PR 1** of
`docs/plans/mcdiarmid-rademacher-plan.md`. It provides only the
filtration, the martingale property, and the `k = 0` boundary
identity. Conditional sub-Gaussianity of the increments (the
conditional Hoeffding lemma) and the McDiarmid concentration bound are
deferred to sub-PRs B2 and B3.

Constraints respected here:
* No `sorry`, no `admit`, no custom `axiom`. All lemmas close.
* No concentration claim, no high-probability claim, no manifest entry.
* The `k = n` (full-σ-algebra) boundary identity is proved as a
  measurable-space equality so consumers can rewrite their conditional
  expectation if they need it; the corresponding `condExp` identity is
  stated only as far as `coordinateSubAlgebra n Z (Fin.last n) = ⊤`,
  not as a claim about absolute uniform deviation.
-/

namespace FormalSLT.Azuma.ExposureMartingale

open MeasureTheory

/-! ### Coordinate σ-algebra on a finite product

`coordinateSubAlgebra n Z k` is the σ-algebra on `Fin n → Z` generated
by the projections `s ↦ s i` for `i : Fin n` with `(i : ℕ) < (k : ℕ)`.
At `k = 0` it is the trivial σ-algebra `⊥`; at `k = Fin.last n` it is
the full product σ-algebra `⊤`. -/

variable (n : ℕ) (Z : Type*) [MeasurableSpace Z]

/-- The sub-σ-algebra of `MeasurableSpace.pi` on `Fin n → Z` generated
by the first `k` coordinates. -/
@[reducible] def coordinateSubAlgebra (k : Fin (n + 1)) : MeasurableSpace (Fin n → Z) :=
  ⨆ (i : Fin n) (_ : (i : ℕ) < (k : ℕ)),
    (inferInstance : MeasurableSpace Z).comap (fun s : Fin n → Z => s i)

variable {n Z}

lemma coordinateSubAlgebra_le_pi (k : Fin (n + 1)) :
    coordinateSubAlgebra n Z k ≤
      (inferInstance : MeasurableSpace (Fin n → Z)) := by
  unfold coordinateSubAlgebra
  refine iSup_le (fun i => iSup_le (fun _ => ?_))
  -- Each coordinate σ-algebra is bounded above by the full pi σ-algebra
  -- because `MeasurableSpace.pi = ⨆ a, comap (eval a)`.
  show (inferInstance : MeasurableSpace Z).comap (fun s : Fin n → Z => s i)
      ≤ MeasurableSpace.pi
  exact le_iSup
    (fun a => (inferInstance : MeasurableSpace Z).comap (fun b : Fin n → Z => b a)) i

lemma coordinateSubAlgebra_mono :
    Monotone (coordinateSubAlgebra n Z) := by
  intro k₁ k₂ hk
  unfold coordinateSubAlgebra
  refine iSup_le (fun i => iSup_le (fun hi => ?_))
  refine le_iSup₂ (f := fun (i : Fin n) (_ : (i : ℕ) < (k₂ : ℕ)) =>
    (inferInstance : MeasurableSpace Z).comap (fun s : Fin n → Z => s i)) i ?_
  exact lt_of_lt_of_le hi hk

/-- At index `0`, no coordinates are exposed: the σ-algebra is trivial. -/
lemma coordinateSubAlgebra_zero :
    coordinateSubAlgebra n Z (0 : Fin (n + 1)) = ⊥ := by
  unfold coordinateSubAlgebra
  apply le_antisymm
  · refine iSup_le (fun i => iSup_le (fun hi => ?_))
    -- (i : ℕ) < ((0 : Fin (n+1)) : ℕ) = 0 is impossible.
    exact absurd hi (by simp)
  · exact bot_le

/-- At index `Fin.last n`, every coordinate is exposed: the σ-algebra
is the full product σ-algebra. -/
lemma coordinateSubAlgebra_last :
    coordinateSubAlgebra n Z (Fin.last n)
      = (inferInstance : MeasurableSpace (Fin n → Z)) := by
  apply le_antisymm
  · exact coordinateSubAlgebra_le_pi (Fin.last n)
  · -- `MeasurableSpace.pi = ⨆ a, comap (eval a)`. Each summand is
    -- bounded above by `coordinateSubAlgebra n Z (Fin.last n)` because
    -- `(i : ℕ) < n` holds for every `i : Fin n`.
    show MeasurableSpace.pi ≤ coordinateSubAlgebra n Z (Fin.last n)
    refine iSup_le (fun i => ?_)
    unfold coordinateSubAlgebra
    refine le_iSup₂ (f := fun (j : Fin n) (_ : (j : ℕ) < ((Fin.last n) : ℕ)) =>
      (inferInstance : MeasurableSpace Z).comap (fun s : Fin n → Z => s j)) i ?_
    -- (i : ℕ) < (Fin.last n : ℕ) = n holds because i : Fin n.
    show (i : ℕ) < ((Fin.last n) : ℕ)
    simp [Fin.val_last, i.is_lt]

/-! ### Coordinate filtration

The σ-algebras `coordinateSubAlgebra n Z k` form a filtration on
`Fin n → Z` indexed by `Fin (n + 1)`. -/

variable (n Z) in
/-- The natural exposure filtration on `Fin n → Z`. -/
def coordinateFiltration :
    Filtration (Fin (n + 1)) (inferInstance : MeasurableSpace (Fin n → Z)) where
  seq := coordinateSubAlgebra n Z
  mono' := coordinateSubAlgebra_mono
  le' := coordinateSubAlgebra_le_pi

@[simp]
lemma coordinateFiltration_apply (k : Fin (n + 1)) :
    (coordinateFiltration n Z) k = coordinateSubAlgebra n Z k := rfl

/-! ### Doob exposure martingale

The Doob martingale `k ↦ μⁿ[f | ℱₖ]` is a martingale w.r.t. the
coordinate filtration, by `MeasureTheory.martingale_condExp`. We do not
re-prove the martingale property; we just instantiate it.

Below, `μ : Measure Z` is a probability measure, and we work with its
finite product `Measure.pi μ` on `Fin n → Z`. -/

variable {μ : Fin n → Measure Z}

/-- The Doob exposure martingale of `f` under `μⁿ`. -/
noncomputable def exposureMartingale (μ : Fin n → Measure Z) (f : (Fin n → Z) → ℝ) :
    Fin (n + 1) → (Fin n → Z) → ℝ :=
  fun k => (Measure.pi μ)[f | coordinateSubAlgebra n Z k]

/-- The exposure martingale is a martingale under the product measure,
provided the product measure is finite (e.g. when `μ` is a probability
measure on `Z`). -/
theorem exposureMartingale_isMartingale
    [IsFiniteMeasure (Measure.pi μ)]
    (f : (Fin n → Z) → ℝ) :
    Martingale (exposureMartingale μ f) (coordinateFiltration n Z)
      (Measure.pi μ) :=
  martingale_condExp f (coordinateFiltration n Z) _

/-- At `k = 0`, the exposure martingale is (a.e.) the constant function
equal to `∫ f dμⁿ`. -/
theorem exposureMartingale_zero_ae
    [IsProbabilityMeasure (Measure.pi μ)]
    (f : (Fin n → Z) → ℝ) :
    exposureMartingale μ f 0
      =ᵐ[Measure.pi μ]
        fun _ => ∫ s, f s ∂(Measure.pi μ) := by
  unfold exposureMartingale
  rw [coordinateSubAlgebra_zero]
  exact Filter.Eventually.of_forall (congr_fun (condExp_bot f))

/-- At `k = Fin.last n`, the exposure martingale equals `f` (a.e.).
This is the terminal identity needed for the telescoping decomposition
`Mₙ - M₀ = f - E[f]` used in McDiarmid's proof. -/
theorem exposureMartingale_last_ae
    [IsFiniteMeasure (Measure.pi μ)]
    {f : (Fin n → Z) → ℝ} (hf : StronglyMeasurable f)
    (hfi : Integrable f (Measure.pi μ)) :
    exposureMartingale μ f (Fin.last n)
      =ᵐ[Measure.pi μ] f := by
  unfold exposureMartingale
  rw [coordinateSubAlgebra_last]
  exact Filter.Eventually.of_forall
    (congr_fun (condExp_of_stronglyMeasurable le_rfl hf hfi))

end FormalSLT.Azuma.ExposureMartingale
