/-
Copyright (c) 2026 Robby Sneiderman. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Robby Sneiderman
-/

import Tengoku.Formalslt.FormalSLT.AnytimeValid.BettingCS

/-!
# Computable wealth-weighted predictable betting mixtures

This module turns a finite catalog of legal predictable betting strategies
into one adaptive master strategy. At time `n`, the master bet is the
wealth-weighted average of the catalog bets using wealth accumulated strictly
before time `n`. It therefore does not inspect the current residual before
choosing its current bet.

The executable definitions are algebraic over a field and contain no choice
operator, infinite sum, integral, logarithm, or exponential. In particular,
their specialization to `Rat` is an exact computation. A separate real bridge
proves that the master wealth is exactly the finite mixture of the component
betting wealth processes. Consequently it is an e-process whenever the
component wealth processes are e-processes and positive prior weights and
strictly positive factors keep the mixture denominator nonzero.

This finite master competes simultaneously with every positive-prior strategy
by the explicit multiplicative price `1 / weight j`. It is not yet a universal
coin-betting or continuum-strategy regret theorem.
-/

open MeasureTheory ProbabilityTheory
open scoped BigOperators

namespace FormalSLT.AnytimeValid

section Algebra

variable {R Omega Kappa : Type*}

/-- Multiplicative betting wealth for an abstract residual and bet process. -/
def algebraicBettingWealth [CommSemiring R]
    (residual bet : Nat -> Omega -> R) (n : Nat) (omega : Omega) : R :=
  ∏ k ∈ Finset.range n, (1 + bet k omega * residual k omega)

/-- Fixed-prior mixture of the wealths generated by a finite strategy
catalog. -/
def finiteExpertMixtureWealth [CommSemiring R]
    [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> R) (residual : Nat -> Omega -> R)
    (strategy : Kappa -> Nat -> Omega -> R) (n : Nat) (omega : Omega) : R :=
  ∑ j : Kappa, weight j *
    algebraicBettingWealth residual (strategy j) n omega

/-- The master bet obtained by normalizing each strategy's prior-weighted
wealth before the current observation is revealed. -/
def wealthWeightedBet [Field R] [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> R) (residual : Nat -> Omega -> R)
    (strategy : Kappa -> Nat -> Omega -> R) (n : Nat) (omega : Omega) : R :=
  (∑ j : Kappa, weight j *
      algebraicBettingWealth residual (strategy j) n omega *
        strategy j n omega) /
    finiteExpertMixtureWealth weight residual strategy n omega

@[simp]
theorem algebraicBettingWealth_zero [CommSemiring R]
    (residual bet : Nat -> Omega -> R) (omega : Omega) :
    algebraicBettingWealth residual bet 0 omega = 1 := by
  simp [algebraicBettingWealth]

theorem algebraicBettingWealth_succ [CommSemiring R]
    (residual bet : Nat -> Omega -> R) (n : Nat) (omega : Omega) :
    algebraicBettingWealth residual bet (n + 1) omega =
      algebraicBettingWealth residual bet n omega *
        (1 + bet n omega * residual n omega) := by
  simp [algebraicBettingWealth, Finset.prod_range_succ]

@[simp]
theorem finiteExpertMixtureWealth_zero [CommSemiring R]
    [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> R) (residual : Nat -> Omega -> R)
    (strategy : Kappa -> Nat -> Omega -> R) (omega : Omega) :
    finiteExpertMixtureWealth weight residual strategy 0 omega =
      ∑ j : Kappa, weight j := by
  simp [finiteExpertMixtureWealth]

/-- The finite mixture update is exactly the old mixture wealth plus the
current residual times the wealth-weighted bet numerator. -/
theorem finiteExpertMixtureWealth_succ [CommSemiring R]
    [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> R) (residual : Nat -> Omega -> R)
    (strategy : Kappa -> Nat -> Omega -> R) (n : Nat) (omega : Omega) :
    finiteExpertMixtureWealth weight residual strategy (n + 1) omega =
      finiteExpertMixtureWealth weight residual strategy n omega +
        residual n omega *
          ∑ j : Kappa, weight j *
            algebraicBettingWealth residual (strategy j) n omega *
              strategy j n omega := by
  unfold finiteExpertMixtureWealth
  simp_rw [algebraicBettingWealth_succ]
  calc
    (∑ j : Kappa, weight j *
        (algebraicBettingWealth residual (strategy j) n omega *
          (1 + strategy j n omega * residual n omega))) =
        ∑ j : Kappa,
          (weight j * algebraicBettingWealth residual (strategy j) n omega +
            residual n omega *
              (weight j * algebraicBettingWealth residual (strategy j) n omega *
                strategy j n omega)) := by
      apply Finset.sum_congr rfl
      intro j _hj
      ring
    _ = (∑ j : Kappa,
          weight j * algebraicBettingWealth residual (strategy j) n omega) +
        ∑ j : Kappa, residual n omega *
          (weight j * algebraicBettingWealth residual (strategy j) n omega *
            strategy j n omega) := Finset.sum_add_distrib
    _ = (∑ j : Kappa,
          weight j * algebraicBettingWealth residual (strategy j) n omega) +
        residual n omega *
          ∑ j : Kappa, weight j *
            algebraicBettingWealth residual (strategy j) n omega *
              strategy j n omega := by rw [Finset.mul_sum]

/-- The wealth of the adaptive master strategy equals the fixed-prior mixture
of all component wealths, at every time and on every path. -/
theorem aggregateWealth_eq_finiteExpertMixtureWealth [Field R]
    [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> R) (residual : Nat -> Omega -> R)
    (strategy : Kappa -> Nat -> Omega -> R)
    (hweight : ∑ j : Kappa, weight j = 1)
    (hmix_ne : forall n omega,
      finiteExpertMixtureWealth weight residual strategy n omega ≠ 0) :
    forall n omega,
      algebraicBettingWealth residual
          (wealthWeightedBet weight residual strategy) n omega =
        finiteExpertMixtureWealth weight residual strategy n omega := by
  intro n
  induction n with
  | zero =>
      intro omega
      simp [hweight]
  | succ n ih =>
      intro omega
      rw [algebraicBettingWealth_succ, ih omega,
        finiteExpertMixtureWealth_succ]
      unfold wealthWeightedBet
      have hne : finiteExpertMixtureWealth weight residual strategy n omega ≠ 0 :=
        hmix_ne n omega
      field_simp [hne]

/-- Nonnegative component wealths make the mixture dominate every
prior-weighted strategy wealth. -/
theorem finiteExpertMixtureWealth_competes [CommSemiring R]
    [PartialOrder R] [IsOrderedRing R]
    [Fintype Kappa] [DecidableEq Kappa]
    {weight : Kappa -> R} {residual : Nat -> Omega -> R}
    {strategy : Kappa -> Nat -> Omega -> R}
    (hweight_nonneg : forall j, 0 <= weight j)
    (hwealth_nonneg : forall j n omega,
      0 <= algebraicBettingWealth residual (strategy j) n omega)
    (j : Kappa) (n : Nat) (omega : Omega) :
    weight j * algebraicBettingWealth residual (strategy j) n omega <=
      finiteExpertMixtureWealth weight residual strategy n omega := by
  unfold finiteExpertMixtureWealth
  exact Finset.single_le_sum
    (fun i _hi => mul_nonneg (hweight_nonneg i) (hwealth_nonneg i n omega))
    (Finset.mem_univ j)

/-- The adaptive master competes with every supplied strategy without a
post-hoc atom selector. -/
theorem aggregateWealth_competes_with_every_strategy [Field R]
    [LinearOrder R] [IsStrictOrderedRing R]
    [Fintype Kappa] [DecidableEq Kappa]
    {weight : Kappa -> R} {residual : Nat -> Omega -> R}
    {strategy : Kappa -> Nat -> Omega -> R}
    (hweight : ∑ j : Kappa, weight j = 1)
    (hweight_nonneg : forall j, 0 <= weight j)
    (hwealth_nonneg : forall j n omega,
      0 <= algebraicBettingWealth residual (strategy j) n omega)
    (hmix_pos : forall n omega,
      0 < finiteExpertMixtureWealth weight residual strategy n omega)
    (j : Kappa) (n : Nat) (omega : Omega) :
    weight j * algebraicBettingWealth residual (strategy j) n omega <=
      algebraicBettingWealth residual
        (wealthWeightedBet weight residual strategy) n omega := by
  rw [aggregateWealth_eq_finiteExpertMixtureWealth
    weight residual strategy hweight
      (fun n omega => (hmix_pos n omega).ne') n omega]
  exact finiteExpertMixtureWealth_competes
    hweight_nonneg hwealth_nonneg j n omega

/-- Strictly positive one-step factors give strictly positive expert wealth. -/
theorem algebraicBettingWealth_pos [Field R]
    [LinearOrder R] [IsStrictOrderedRing R]
    {residual bet : Nat -> Omega -> R}
    (hfactor_pos : forall k omega,
      0 < 1 + bet k omega * residual k omega)
    (n : Nat) (omega : Omega) :
    0 < algebraicBettingWealth residual bet n omega := by
  unfold algebraicBettingWealth
  exact Finset.prod_pos fun k _hk => hfactor_pos k omega

/-- Positive prior weights and positive component factors make the master
mixture denominator strictly positive. -/
theorem finiteExpertMixtureWealth_pos [Field R]
    [LinearOrder R] [IsStrictOrderedRing R]
    [Fintype Kappa] [DecidableEq Kappa] [Nonempty Kappa]
    {weight : Kappa -> R} {residual : Nat -> Omega -> R}
    {strategy : Kappa -> Nat -> Omega -> R}
    (hweight_pos : forall j, 0 < weight j)
    (hfactor_pos : forall j k omega,
      0 < 1 + strategy j k omega * residual k omega)
    (n : Nat) (omega : Omega) :
    0 < finiteExpertMixtureWealth weight residual strategy n omega := by
  unfold finiteExpertMixtureWealth
  exact Finset.sum_pos
    (fun j _hj => mul_pos (hweight_pos j)
      (algebraicBettingWealth_pos (hfactor_pos j) n omega))
    Finset.univ_nonempty

/-- A convex catalog of nonnegative bounded bets produces a legal master bet
in the same interval. -/
theorem wealthWeightedBet_mem_Icc [Field R]
    [LinearOrder R] [IsStrictOrderedRing R]
    [Fintype Kappa] [DecidableEq Kappa]
    {weight : Kappa -> R} {residual : Nat -> Omega -> R}
    {strategy : Kappa -> Nat -> Omega -> R} {limit : R}
    (hweight_nonneg : forall j, 0 <= weight j)
    (hwealth_nonneg : forall j n omega,
      0 <= algebraicBettingWealth residual (strategy j) n omega)
    (hmix_pos : forall n omega,
      0 < finiteExpertMixtureWealth weight residual strategy n omega)
    (hstrategy : forall j n omega,
      strategy j n omega ∈ Set.Icc (0 : R) limit)
    (n : Nat) (omega : Omega) :
    wealthWeightedBet weight residual strategy n omega ∈
      Set.Icc (0 : R) limit := by
  let coefficient : Kappa -> R := fun j =>
    weight j * algebraicBettingWealth residual (strategy j) n omega
  have hcoefficient : forall j, 0 <= coefficient j := fun j =>
    mul_nonneg (hweight_nonneg j) (hwealth_nonneg j n omega)
  have hnum_nonneg : 0 <=
      ∑ j : Kappa, coefficient j * strategy j n omega :=
    Finset.sum_nonneg fun j _hj =>
      mul_nonneg (hcoefficient j) (hstrategy j n omega).1
  have hnum_le :
      (∑ j : Kappa, coefficient j * strategy j n omega) <=
        limit * finiteExpertMixtureWealth weight residual strategy n omega := by
    calc
      (∑ j : Kappa, coefficient j * strategy j n omega) <=
          ∑ j : Kappa, coefficient j * limit := by
        exact Finset.sum_le_sum fun j _hj =>
          mul_le_mul_of_nonneg_left (hstrategy j n omega).2 (hcoefficient j)
      _ = limit * finiteExpertMixtureWealth
          weight residual strategy n omega := by
        unfold coefficient finiteExpertMixtureWealth
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro j _hj
        ring
  unfold wealthWeightedBet
  change
    (∑ j : Kappa, coefficient j * strategy j n omega) /
        finiteExpertMixtureWealth weight residual strategy n omega ∈
      Set.Icc (0 : R) limit
  exact ⟨div_nonneg hnum_nonneg (hmix_pos n omega).le,
    (div_le_iff₀ (hmix_pos n omega)).2 hnum_le⟩

end Algebra

section RationalBridge

variable {Omega Kappa : Type*}

/-- Exact rational expert wealth casts to the corresponding real wealth. -/
theorem ratCast_algebraicBettingWealth
    (residual bet : Nat -> Omega -> Rat) (n : Nat) (omega : Omega) :
    ((algebraicBettingWealth residual bet n omega : Rat) : Real) =
      algebraicBettingWealth
        (fun k omega => (residual k omega : Real))
        (fun k omega => (bet k omega : Real)) n omega := by
  simp [algebraicBettingWealth]

/-- Exact rational finite-mixture wealth casts to the same real finite
mixture, term for term. -/
theorem ratCast_finiteExpertMixtureWealth
    [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> Rat) (residual : Nat -> Omega -> Rat)
    (strategy : Kappa -> Nat -> Omega -> Rat) (n : Nat) (omega : Omega) :
    ((finiteExpertMixtureWealth weight residual strategy n omega : Rat) : Real) =
      finiteExpertMixtureWealth
        (fun j => (weight j : Real))
        (fun k omega => (residual k omega : Real))
        (fun j k omega => (strategy j k omega : Real)) n omega := by
  simp [finiteExpertMixtureWealth, ratCast_algebraicBettingWealth]

/-- The executable rational master bet casts exactly to the real master bet
used by the analytic e-process layer. -/
theorem ratCast_wealthWeightedBet
    [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> Rat) (residual : Nat -> Omega -> Rat)
    (strategy : Kappa -> Nat -> Omega -> Rat) (n : Nat) (omega : Omega) :
    ((wealthWeightedBet weight residual strategy n omega : Rat) : Real) =
      wealthWeightedBet
        (fun j => (weight j : Real))
        (fun k omega => (residual k omega : Real))
        (fun j k omega => (strategy j k omega : Real)) n omega := by
  simp [wealthWeightedBet, ratCast_finiteExpertMixtureWealth,
    ratCast_algebraicBettingWealth]

end RationalBridge

section RealBridge

variable {Omega Kappa : Type*}

/-- The algebraic wealth specialized to residual `X - m` is the existing
betting wealth process definition. -/
theorem algebraicBettingWealth_eq_bettingWealthProcess
    (X bet : Nat -> Omega -> Real) (m : Real) (n : Nat) (omega : Omega) :
    algebraicBettingWealth (fun k omega => X k omega - m) bet n omega =
      bettingWealthProcess X bet m n omega := by
  rfl

/-- The algebraic finite mixture is the library's finite weighted process of
the component betting wealths. -/
theorem finiteExpertMixtureWealth_eq_finiteWeightedProcess
    [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> Real) (X : Nat -> Omega -> Real) (m : Real)
    (strategy : Kappa -> Nat -> Omega -> Real) (n : Nat) (omega : Omega) :
    finiteExpertMixtureWealth weight (fun k omega => X k omega - m)
        strategy n omega =
      finiteWeightedProcess weight
        (fun j => bettingWealthProcess X (strategy j) m) n omega := by
  unfold finiteExpertMixtureWealth finiteWeightedProcess
  apply Finset.sum_congr rfl
  intro j _hj
  rw [algebraicBettingWealth_eq_bettingWealthProcess]

/-- The wealth-weighted master bet is predictable: its current weights use
only component wealth accumulated before the current observation. -/
theorem wealthWeightedBet_stronglyAdapted
    {mOmega : MeasurableSpace Omega} {F : Filtration Nat mOmega}
    [Fintype Kappa] [DecidableEq Kappa]
    (weight : Kappa -> Real) (X : Nat -> Omega -> Real) (m : Real)
    (strategy : Kappa -> Nat -> Omega -> Real)
    (hX_adapted : IncrementAdapted F X)
    (hstrategy_adapted : forall j, StronglyAdapted F (strategy j)) :
    StronglyAdapted F
      (wealthWeightedBet weight (fun k omega => X k omega - m) strategy) := by
  intro n
  have hwealth (j : Kappa) : StronglyMeasurable[F n]
      (fun omega => algebraicBettingWealth
        (fun k omega => X k omega - m) (strategy j) n omega) := by
    simpa only [algebraicBettingWealth_eq_bettingWealthProcess] using
      (stronglyAdapted_bettingWealthProcess_of_adapted
        hX_adapted (hstrategy_adapted j) n)
  have hnumerator : StronglyMeasurable[F n]
      (∑ j : Kappa, fun omega =>
        weight j * algebraicBettingWealth
          (fun k omega => X k omega - m) (strategy j) n omega *
            strategy j n omega) := by
    exact Finset.stronglyMeasurable_sum Finset.univ fun j _hj =>
      ((hwealth j).const_mul (weight j)).mul (hstrategy_adapted j n)
  have hdenominator : StronglyMeasurable[F n]
      (∑ j : Kappa, fun omega =>
        weight j * algebraicBettingWealth
          (fun k omega => X k omega - m) (strategy j) n omega) := by
    exact Finset.stronglyMeasurable_sum Finset.univ fun j _hj =>
      (hwealth j).const_mul (weight j)
  have heq :
      wealthWeightedBet weight (fun k omega => X k omega - m) strategy n =
        fun omega =>
          (∑ j : Kappa,
              weight j * algebraicBettingWealth
                (fun k omega => X k omega - m) (strategy j) n omega *
                  strategy j n omega) /
            (∑ j : Kappa,
              weight j * algebraicBettingWealth
                (fun k omega => X k omega - m) (strategy j) n omega) := by
    funext omega
    rfl
  rw [heq]
  have hdiv := hnumerator.div hdenominator
  convert hdiv using 1
  funext omega
  simp only [Finset.sum_apply, Pi.div_apply]

/-- The adaptive master's betting wealth is an e-process whenever every
component betting wealth is an e-process and the pathwise mixture denominator
is positive. -/
theorem wealthWeightedBet_eProcess
    {mOmega : MeasurableSpace Omega} {mu : Measure Omega}
    {F : Filtration Nat mOmega}
    [Fintype Kappa] [DecidableEq Kappa] [IsFiniteMeasure mu]
    (weight : Kappa -> Real)
    (hweight_nonneg : forall j, 0 <= weight j)
    (hweight_sum_one : ∑ j : Kappa, weight j = 1)
    (X : Nat -> Omega -> Real) (m : Real)
    (strategy : Kappa -> Nat -> Omega -> Real)
    (hcomponent : forall j,
      EProcess mu F (bettingWealthProcess X (strategy j) m))
    (hmix_pos : forall n omega, 0 < finiteExpertMixtureWealth weight
      (fun k omega => X k omega - m) strategy n omega) :
    EProcess mu F
      (bettingWealthProcess X
        (wealthWeightedBet weight (fun k omega => X k omega - m) strategy)
        m) := by
  have hmix : EProcess mu F
      (finiteWeightedProcess weight
        (fun j => bettingWealthProcess X (strategy j) m)) :=
    finiteWeightedProcess_eProcess hweight_nonneg hweight_sum_one hcomponent
  have heq :
      bettingWealthProcess X
          (wealthWeightedBet weight (fun k omega => X k omega - m) strategy)
          m =
        finiteWeightedProcess weight
          (fun j => bettingWealthProcess X (strategy j) m) := by
    funext n omega
    rw [← algebraicBettingWealth_eq_bettingWealthProcess]
    rw [aggregateWealth_eq_finiteExpertMixtureWealth
      weight (fun k omega => X k omega - m) strategy hweight_sum_one
        (fun n omega => (hmix_pos n omega).ne') n omega]
    exact finiteExpertMixtureWealth_eq_finiteWeightedProcess
      weight X m strategy n omega
  rw [heq]
  exact hmix

/-- E-process closure with mixture positivity discharged by positive prior
weights and strictly positive component betting factors. -/
theorem wealthWeightedBet_eProcess_of_positive_factors
    {mOmega : MeasurableSpace Omega} {mu : Measure Omega}
    {F : Filtration Nat mOmega}
    [Fintype Kappa] [DecidableEq Kappa] [Nonempty Kappa]
    [IsFiniteMeasure mu]
    (weight : Kappa -> Real)
    (hweight_pos : forall j, 0 < weight j)
    (hweight_sum_one : ∑ j : Kappa, weight j = 1)
    (X : Nat -> Omega -> Real) (m : Real)
    (strategy : Kappa -> Nat -> Omega -> Real)
    (hcomponent : forall j,
      EProcess mu F (bettingWealthProcess X (strategy j) m))
    (hfactor_pos : forall j k omega,
      0 < bettingFactor X (strategy j) m k omega) :
    EProcess mu F
      (bettingWealthProcess X
        (wealthWeightedBet weight (fun k omega => X k omega - m) strategy)
        m) := by
  apply wealthWeightedBet_eProcess weight (fun j => (hweight_pos j).le)
    hweight_sum_one X m strategy hcomponent
  intro n omega
  exact finiteExpertMixtureWealth_pos hweight_pos
    (fun j k omega => by
      simpa only [bettingFactor] using hfactor_pos j k omega)
    n omega

/-- Log-wealth regret of the adaptive master relative to any supplied
strategy is at most the strategy's negative log prior weight. -/
theorem aggregate_logWealth_regret_le
    [Fintype Kappa] [DecidableEq Kappa]
    {weight : Kappa -> Real} {residual : Nat -> Omega -> Real}
    {strategy : Kappa -> Nat -> Omega -> Real}
    (hweight_sum_one : ∑ j : Kappa, weight j = 1)
    (hweight_nonneg : forall j, 0 <= weight j)
    (hwealth_nonneg : forall j n omega,
      0 <= algebraicBettingWealth residual (strategy j) n omega)
    (hmix_pos : forall n omega,
      0 < finiteExpertMixtureWealth weight residual strategy n omega)
    {j : Kappa} (hweight_pos : 0 < weight j)
    {n : Nat} {omega : Omega}
    (hexpert_pos :
      0 < algebraicBettingWealth residual (strategy j) n omega) :
    Real.log (algebraicBettingWealth residual (strategy j) n omega) -
        Real.log (algebraicBettingWealth residual
          (wealthWeightedBet weight residual strategy) n omega) <=
      -Real.log (weight j) := by
  have hcomp := aggregateWealth_competes_with_every_strategy
    hweight_sum_one hweight_nonneg hwealth_nonneg hmix_pos j n omega
  have hlog := Real.log_le_log (mul_pos hweight_pos hexpert_pos) hcomp
  rw [Real.log_mul hweight_pos.ne' hexpert_pos.ne'] at hlog
  linarith

end RealBridge

end FormalSLT.AnytimeValid
