-- Tengoku.EquationalTheories.Sheffer: verified translations of equational_theories/Sheffer.lean (1 theorem)
import Tengoku.EquationalTheories.Deps.Magma
import Lean
import Tengoku.Seed.Data.FunLike.Basic
import Tengoku.Seed.Logic.Equiv.Basic
import Tengoku.Seed.Data.List.NodupEquivFin
import Tengoku.Seed.Data.Set.Defs
import Lean.Elab.Exception
import Lean.Elab.Declaration
import Lean.Util.CollectAxioms
import Lean.Environment
import Lean.Meta.Basic
import Lean.Util
import Tengoku.EquationalTheories.Deps.Superposition
import Tengoku.Seed.Order.BooleanAlgebra.Set
import Tengoku.EquationalTheories.Deps.Equations

set_option linter.all false

namespace EquationalTheories

/-
Copyright (c) 2024 Cody Roux. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cody Roux, Judah Towery
-/

/-!
This file formalizes the main result of [McCune & al. Short Single Axioms for Boolean Algebra]
https://www.cs.unm.edu/~mccune/papers/basax/v12.pdf, namely that an abstract boolean
algebra (such as defined by the `BooleanAlgebra` typeclass) can be axiomatized with a
single binary operation, the Sheffer stroke, satisfying a single equation, Equation345169,
which we recall here:  x = (y ◇ ((x ◇ y) ◇ y)) ◇ (x ◇ (z ◇ y)). It is the shortest
such axiom in terms of number of symbols, though we do not prove this here.

The proof in one direction is somewhat trivial, as the axioms for join and complement can
simply be unfolded to prove the equation. The other direction is quite a bit more involved,
and uses several proofs generated by Vampire (Otter was used in the original paper proof).
See `Generated/VampireProven/Sheffer.lean` for the proofs generated by Vampire.

The strategy involves proving the 3 axioms in the definition of the Sheffer stroke, and using
a seperate proof that such an axiomatization fully characterizes Boolean algebras
(found in `ShefferAlgebra.lean`).
-/

namespace Sheffer

open Sheffer

/- Sheffer stroke magma on a Boolean algebra -/
instance (B : Type*) [BooleanAlgebra B] : Magma B where
  op a b := (a ⊓ b)ᶜ

lemma Sheffer_Op (B : Type*) [BooleanAlgebra B] (a b : B) : a ◇ b = (a ⊓ b)ᶜ
:= rfl

end Sheffer

end EquationalTheories
