#!/usr/bin/env python3
"""classify.py <base> <head> — one purpose per PR.
Assigns the PR a class from the paths it touches: content, tombstone, tooling,
docs. `docs` may ride along with any other class. Two other classes, or any
derived file (generated modules, stats, cache pointer) → fail."""

from __future__ import annotations

import os
import sys

from _git import changed_files, fail, gh_output, tier_of

base, head = sys.argv[1], sys.argv[2]
files = changed_files(base, head)
if not files:
    fail("empty diff")
by = {}
for st, p in files:
    by.setdefault(tier_of(p), []).append(p)
derived = by.get("derived")
bot = os.environ.get("TENGOKU_BOT", "tengoku-bot")
actor = os.environ.get("PR_ACTOR", "")
# The promote bot's PRs move staging records to trusted and regenerate modules: derived + content + tombstone paths, nothing else.
if set(by) <= {"derived", "content", "tombstone"} and (derived or by.get("tombstone")) and actor == bot:
    print(f"class=promotion ({len(files)} files, by {actor})")
    gh_output("class", "promotion")
    gh_output("files", " ".join(p for _, p in files))
    sys.exit(0)
if derived:
    fail("derived files are regenerated by the promote bot, never edited in a PR: " + ", ".join(derived[:5]))
classes = [c for c in by if c != "docs"] or ["docs"]
if len(classes) > 1:
    detail = "; ".join(f"{c}: {', '.join(by[c][:3])}" for c in classes)
    fail(f"multi-purpose PR ({' + '.join(classes)}). One purpose per PR. {detail}")
cls = classes[0]
print(f"class={cls} ({len(files)} files)")
gh_output("class", cls)
gh_output("files", " ".join(p for _, p in files))
