#!/usr/bin/env python3
"""gate_summary.py — one comment per PR that explains the gate's verdict.

Runs in the `pr-gate` summary job after every other job. Reads this run's jobs
and steps, quotes the first error line of each failed job, says what the check
looks for and what to do, and for the checks that are complex enough to be wrong
themselves adds a prefilled "Report a gate bug" issue link. The comment is
upserted (one per PR, found by a marker) and the same text goes to the job
summary. Without a PR number (merge groups) only the job summary is written.

This is the one job that writes to the PR, and everything it quotes comes from other jobs' logs and annotations: text a PR
author influences. It is data here, quoted inside a code fence that the quoted text cannot close, never interpreted.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import urllib.parse

MARK = "<!-- tengoku-gate-summary -->"
REPO = os.environ.get("GITHUB_REPOSITORY", "")
RUN = os.environ.get("GITHUB_RUN_ID", "")
SERVER = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
PR = os.environ.get("PR_NUMBER", "").strip()
HEAD = os.environ.get("HEAD_SHA", "")[:8]
CLASS = os.environ.get("PR_CLASS", "") or "unclassified"
# The ruleset requires every review conversation to be resolved before a merge. GitHub's banner only says
# "A conversation must be resolved", which newcomers don't connect to the AI reviewers' comments.
CONVERSATIONS = (
    "**Before it can merge:** every review conversation must be resolved, including the AI reviewer's "
    "(CodeRabbit). Read each one, fix what applies or reply saying why not, then press "
    "**Resolve conversation** under it. As the PR's author you can resolve them yourself."
)

# job -> (fragility, what it checks, what to do). Fragility "high" or "medium" adds the report link:
# those checks reason about paths, text patterns or other services and can misfire; "low" ones are exact.
ADVICE: dict[str, tuple[str, str, str]] = {
    "classify": (
        "high",
        "one purpose per PR, read from the paths you touched (content, tombstone, tooling, docs; derived files are regenerated by the bot)",
        "split the PR so it touches one tier, and never edit `Tengoku/<Library>/**`, `Tengoku/All.lean` or `data/stats.json` by hand; docs may ride along with anything",
    ),
    "append-only": (
        "medium",
        "data files only grow: every existing byte stays, new lines go at the end",
        "re-open the file and append; an editor that reformats JSON, reorders lines or changes line endings trips this",
    ),
    "records": (
        "medium",
        "each added record against `schemas/record.schema.json`: required fields, allowed source, identifier name declared by its statement, no duplicate or already-trusted name; tombstones name an existing record",
        "fix the line the message names; for a new source, add it to `schemas/sources.json` in a tooling PR first",
    ),
    "content-lint": (
        "medium",
        "no construct that runs or links code inside `context`, `statement` or `proof` (`import`, `#eval`, `initialize`, `unsafe`, `native_decide`, `axiom`, options off the allowlist)",
        "remove the construct; the lint matches text, so a forbidden word inside a comment or string trips it too — that is a false positive worth reporting",
    ),
    "credits": (
        "high",
        "no removed or changed line that carries an authorship or provenance marker (`Authors:`, `Copyright`, `source_url`, …)",
        "restore the line; if the line only *contains* one of those words and is not a credit, this is a false positive of the text rule",
    ),
    "secrets": (
        "medium",
        "no credential-shaped string anywhere in the change (verified secrets, and pattern matches such as key ids, tokens, private keys)",
        "remove it and rotate it if it was real; a high-entropy string that is not a secret is a known false-positive class — report it and a maintainer adds it to `.secrets.baseline`",
    ),
    "dco": ("low", "every commit carries `Signed-off-by:`", "`git commit -s --amend` (or `git rebase --signoff`) and push"),
    "goals": (
        "medium",
        "GOALS.md keeps its shape (ids, status, the standard fields, one Suggestions part per goal), every `tengoku:Name` exists and links are http(s); the AI reviewer's PRs change only Suggestions",
        "fix what the message names; the format and a block to copy are in docs/goals.md",
    ),
    "vacuity": (
        "medium",
        "each new theorem the queue would compile: can `False` be derived from its hypotheses alone (omega, simp_all, decide, linarith, positivity, grind, aesop)? Such a theorem proves nothing",
        "fix the hypothesis and push, or, if it is intended, add `Vacuous-Ack: <theorem>: <why>` to the description for each; the gate re-runs on a description edit",
    ),
    "workflows": (
        "medium",
        "the workflow and action files you add or change: actions pinned to a full commit with the tag as a comment, and that tag really "
        "contains the commit; checkouts drop their token; `permissions: {}` at the top; no `${{ }}` that can carry text inside a script; "
        "no PR code checked out or run by a pull_request_target workflow",
        "fix the line the message names (`scripts/ci/workflow_rules.py` explains each rule); run `python3 scripts/ci/workflow_rules.py --online "
        ".github/workflows` locally",
    ),
    "depends": (
        "medium",
        "`Depends-On: #N` lines in the description point at PRs that are merged or already queued",
        "wait for #N, or queue it first; the gate re-runs when the description or the branch changes",
    ),
    "lint-python": (
        "low",
        "`pre-commit run --all-files` (ruff, formatting, hooks) on tooling changes",
        "run it locally and commit the result",
    ),
    "tooling-tests": (
        "medium",
        "the gate scripts' own unit tests and `actionlint` on workflows",
        "run `python3 -m unittest scripts.ci.tests.test_gates` and `actionlint` locally",
    ),
    "data-rules": ("medium", "append-only, record validation and content lint", "see the step named below"),
}


def gh(*args: str) -> str:
    r = subprocess.run(["gh", *args], capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else ""


def jobs() -> list[dict]:
    out = gh("run", "view", RUN, "-R", REPO, "--json", "jobs")
    return json.loads(out)["jobs"] if out else []


def excerpt(job_id: int) -> str:
    # A job is a check run; its `::error::` lines are annotations, readable while the run is still in progress.
    ann = gh("api", f"repos/{REPO}/check-runs/{job_id}/annotations", "-q", '.[] | select(.annotation_level=="failure") | .message')
    msgs = [m for m in ann.split("\n") if m.strip() and "Process completed with exit code" not in m]
    if msgs:
        return "\n".join(msgs)[:1200]
    # Fallback: the per-job log (`gh run view --log` refuses while the run is in progress).
    log = gh("api", f"repos/{REPO}/actions/jobs/{job_id}/logs")
    lines = []
    for raw in log.splitlines():
        line = re.sub(r"^[^\t]*\t[^\t]*\t", "", raw)  # tolerate gh's "job\tstep\t" prefix too
        line = re.sub(r"^\S+Z ", "", line)  # timestamp
        line = re.sub(r"\x1b\[[0-9;]*m", "", line)
        if re.search(r"^(FAIL:|##\[error\]|error:)|^\s+\S.*:\d+: ", line) and "Process completed with exit code" not in line:
            lines.append(line.replace("##[error]", "").strip())
        elif lines and line.startswith("  ") and len(lines) < 6:
            lines.append(line.rstrip())
        if len(lines) >= 6:
            break
    return "\n".join(lines[:6])


def fenced(text: str) -> str:
    """Text for a code fence that the text itself cannot close."""
    return text.replace("```", "'''")


def log_lines(log: str) -> list[str]:
    """A job log without gh's prefixes, timestamps and colour codes."""
    out = []
    for raw in log.splitlines():
        line = re.sub(r"^[^\t]*\t[^\t]*\t", "", raw)
        line = re.sub(r"^\S+Z ", "", line)
        out.append(re.sub(r"\x1b\[[0-9;]*m", "", line))
    return out


def advisory_hits(lines: list[str], limit: int = 20) -> list[str]:
    """The `- path:line — name` lines sorry_scan.py prints under its heading: at most `limit`, each cut to 200 characters."""
    hits, seen = [], False
    for line in lines:
        if line.startswith("### sorry / admit"):
            seen = True
        elif seen and line.startswith("- "):
            hits.append(line[:200])
    return hits[:limit]


def advisory(all_jobs: list[dict]) -> str:
    """What the advisory job found, for the comment. It holds no token to say it itself, so this job reads it from the log."""
    job = next((j for j in all_jobs if j.get("name") == "sorry-advisory" and j.get("conclusion") == "success"), None)
    hits = advisory_hits(log_lines(gh("api", f"repos/{REPO}/actions/jobs/{job['databaseId']}/logs"))) if job else []
    if not hits:
        return ""
    return "### sorry / admit in this PR (advisory: the merge queue's build decides)\n\n```text\n" + fenced("\n".join(hits)) + "\n```"


def issue_link(job: str, step: str, text: str) -> str:
    title = f"gate bug? {job}/{step} on PR #{PR or '?'}"
    body = f"PR: {SERVER}/{REPO}/pull/{PR}\nRun: {SERVER}/{REPO}/actions/runs/{RUN}\nCheck: {job} / {step}\n\nWhat it said:\n```\n{text[:800]}\n```\n\nWhy I think the check is wrong:\n"
    q = urllib.parse.urlencode({"labels": "gate-bug", "title": title, "body": body})
    return f"{SERVER}/{REPO}/issues/new?{q}"


def render(all_jobs: list[dict], extra: str = "") -> tuple[str, bool]:
    failed = [j for j in all_jobs if j.get("conclusion") == "failure" and j.get("name") not in ("pr-gate", "sorry-advisory")]
    tail = f"\n\n{extra}" if extra else ""
    if not failed:
        return (
            f"{MARK}\n### Gate: all checks passed for a `{CLASS}` PR at `{HEAD}`\n\nThe merge queue builds only what this PR changes; see CONTRIBUTING.md for what it does.\n\n{CONVERSATIONS}{tail}",
            False,
        )
    out = [MARK, f"### Gate: {len(failed)} check{'s' if len(failed) != 1 else ''} failed for a `{CLASS}` PR at `{HEAD}`", ""]
    for j in failed:
        steps = [s["name"] for s in j.get("steps", []) if s.get("conclusion") == "failure"]
        step = steps[0] if steps else "?"
        key = step if step in ADVICE else j["name"]
        fragility, checks, todo = ADVICE.get(key, ("medium", "see the job log", "open the run and read the failing step"))
        text = excerpt(j["databaseId"])
        out += [f"**{j['name']}** → step *{step}*", "", f"Checks: {checks}.", ""]
        if text:
            out += ["```text", fenced(text), "```", ""]
        out += [f"**What to do:** {todo}.", ""]
        if fragility in ("high", "medium"):
            out += [
                f"This check reasons about {'paths' if key == 'classify' else 'text patterns or other services'} and can be wrong. If your change is right and the check is not: **[Report a gate bug]({issue_link(j['name'], step, text)})** — a maintainer looks at every one.",
                "",
            ]
    out += [f"Run: {SERVER}/{REPO}/actions/runs/{RUN} · after fixing, push and the gate re-runs.", "", CONVERSATIONS]
    return "\n".join(out) + tail, True


def upsert_comment(body: str) -> None:
    if not PR:
        return
    existing = gh("api", f"repos/{REPO}/issues/{PR}/comments", "--paginate", "-q", f'.[] | select(.body | startswith("{MARK}")) | .id')
    cid = existing.split()[0] if existing.strip() else ""
    with open("gate-summary.md", "w", encoding="utf-8") as f:
        f.write(body)
    if cid:
        subprocess.run(
            ["gh", "api", "-X", "PATCH", f"repos/{REPO}/issues/comments/{cid}", "-F", "body=@gate-summary.md"], capture_output=True
        )
    else:
        subprocess.run(
            ["gh", "api", "-X", "POST", f"repos/{REPO}/issues/{PR}/comments", "-F", "body=@gate-summary.md"], capture_output=True
        )


def main() -> int:
    if "--render-test" in sys.argv:  # tests: jobs JSON on stdin, no network
        body, _ = render(json.load(sys.stdin))
        print(body)
        return 0
    all_jobs = jobs()
    body, failed = render(all_jobs, advisory(all_jobs))
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as f:
            f.write(body.replace(MARK, "") + "\n")
    upsert_comment(body)
    print(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
