#!/usr/bin/env bash
# Create (or update) the class labels the gate puts on every PR: scripts/ci/classify.py decides the class,
# the pr-gate `classify` job applies it. Run once per repository by a maintainer: scripts/ci/labels.sh [owner/repo]
set -euo pipefail
repo="${1:-competemath/tengoku}"
label() {
  local name="$1" color="$2" description="$3"
  gh label create "$name" -R "$repo" --color "$color" --description "$description" --force
}
label content   0e8a16 "Records: tentative or staging data"
label tombstone d93f0b "Retracts trusted records"
label promotion 5319e7 "Bot: staging records promoted to trusted, with their regenerated modules"
label intake    1d76db "Bot: a verified library bundle from the translation factory (Lean modules + manifest)"
label scope-fix 1d76db "Bot: a merged library's global instances/simp lemmas made local (checked line by line)"
label tooling   1d76db "Scripts, workflows, schemas, build files"
label docs      c5def5 "Documentation only"
label derived   bfd4f2 "Generated files (regenerated by the bot, never edited by hand)"
