/-
Copyright (c) 2026 Devon Tuma. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/
module

public import Tengoku
public import Tengoku.Std
public import Tengoku.Tactic.Aesop
public import Tengoku.Meta.Qq

/-!
# The measurable coproduct structure on `Except`

`Except ε α` is given the coproduct measurable space generated by its `error` and `ok`
constructors. This is the measurable structure needed to retain exceptions as outcomes when
interpreting `ExceptT` probabilistically.
-/

@[expose] public section

open MeasureTheory

namespace Except

variable {ε α β : Type*}

/-- The coproduct measurable space on `Except ε α`. -/
instance instMeasurableSpace [mε : MeasurableSpace ε] [mα : MeasurableSpace α] :
    MeasurableSpace (Except ε α) :=
  mε.map error ⊓ mα.map ok

@[fun_prop]
theorem measurable_error [MeasurableSpace ε] [MeasurableSpace α] :
    Measurable (@error ε α) :=
  Measurable.of_le_map inf_le_left

@[fun_prop]
theorem measurable_ok [MeasurableSpace ε] [MeasurableSpace α] :
    Measurable (@ok ε α) :=
  Measurable.of_le_map inf_le_right

/-- A function out of `Except ε α` is measurable when both constructor branches are. -/
theorem measurable_elim [MeasurableSpace ε] [MeasurableSpace α] [MeasurableSpace β]
    {f : Except ε α → β} (hError : Measurable (f ∘ error))
    (hOk : Measurable (f ∘ ok)) : Measurable f :=
  Measurable.of_comap_le <| le_inf
    (MeasurableSpace.comap_le_iff_le_map.2 hError)
    (MeasurableSpace.comap_le_iff_le_map.2 hOk)

/-- Mapping the successful value of an exception preserves measurability. -/
@[fun_prop]
theorem measurable_map [MeasurableSpace ε] [MeasurableSpace α] [MeasurableSpace β]
    {f : α → β} (hf : Measurable f) : Measurable (Except.map (ε := ε) f) :=
  measurable_elim measurable_error (measurable_ok.comp hf)

end Except
