/-
Copyright (c) 2024 Gian Cordana Sanjaya. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Gian Cordana Sanjaya
-/

module
public import Tengoku.Imoshortlist.IMOSLLean4.Generalization.IMO2012A5.A5Defs
public import Tengoku

/-!
# IMO 2012 A5 (Lift to commutative subrings)

Let `f : R → S` be a non-trivial good function, and fix `x : R`.
We lift `f` to `f' : ℤ[x] → S'` for some commutative subring `S' ⊆ S`.
This is useful as this allows us to generalize commutative-based results.
-/

@[expose] public section

namespace IMOSL
namespace IMO2012A5
namespace Generalization
namespace CommSubring

/-! ### Restricting `S` to the subring generated by `f(R)` -/

section

variable [CommSemiring R] [Ring S]

def codomainLift (f : R → S) (x : R) : Subring.closure (Set.range f) :=
  ⟨f x, Subring.subset_closure (Set.mem_range_self x)⟩

lemma codomainLift_is_good {f : R → S} (hf : good f) : good (codomainLift f) :=
  λ a b ↦ Subtype.ext (hf a b)

lemma codomainLift_is_NontrivialGood {f : R → S} (hf : NontrivialGood f) :
    NontrivialGood (codomainLift f) :=
  ⟨codomainLift_is_good hf.is_good, Subtype.ext hf.map_zero_add_one⟩

end

/-! ### Restricting `R` to subring generated by one element -/

variable [Ring R] [Ring S] (c : R)

def oneVarDomainLift (f : R → S) (x : Subring.closure {c}) : S := f x

abbrev OneVarRange (f : R → S) : Type* :=
  Subring.closure (Set.range (oneVarDomainLift c f))

def oneVarCommLift (f : R → S) : Subring.closure {c} → OneVarRange c f :=
  codomainLift (oneVarDomainLift c f)
