#!/usr/bin/env python3
"""coverage_table.py [--out FILE] — where every registered library stands, counted from the data files.

Reads data/trusted/ and data/staging/ (records counted, tombstones left out), data/stats.json (the tentative count, which
is not re-counted: data/tentative is gigabytes) and schemas/sources.json (which sources have a corpus the library can
compile). Writes a markdown page, so that the numbers in prose are generated, never typed.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def count_records(tier: str) -> dict[str, int]:
    """Records per library in data/<tier>/ (a library's file, or the files of its directory), tombstones excluded."""
    counts: Counter[str] = Counter()
    for f in sorted((ROOT / "data" / tier).rglob("*.jsonl")):
        lib = f.parent.name if f.parent != ROOT / "data" / tier else f.stem
        for line in f.read_text(encoding="utf-8").splitlines():
            if line.strip() and "tombstone" not in json.loads(line):
                counts[lib] += 1
    return dict(counts)


def table(rows: list[tuple]) -> list[str]:
    out = ["| Library | Trusted | Staging | Tentative |", "|---|---:|---:|---:|"]
    out += [f"| `{lib}` | {t:,} | {s:,} | {e:,} |" for lib, t, s, e in rows]
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path)
    a = ap.parse_args()
    trusted, staging = count_records("trusted"), count_records("staging")
    stats = json.loads((ROOT / "data" / "stats.json").read_text(encoding="utf-8"))
    tentative = {lib: c.get("tentative", 0) for lib, c in stats["libraries"].items()}
    corpora = sorted(json.loads((ROOT / "schemas" / "sources.json").read_text(encoding="utf-8"))["corpora"])
    rows = [(lib, trusted.get(lib, 0), staging.get(lib, 0), tentative.get(lib, 0)) for lib in corpora]
    translated = [r for r in rows if r[1] or r[2]]
    tentative_only = [r for r in rows if not r[1] and not r[2] and r[3]]
    empty = [r for r in rows if not (r[1] or r[2] or r[3])]
    out = [
        "# Where the registered libraries stand",
        "",
        f"Generated by `scripts/coverage_table.py` on {date.today()}: trusted and staging counted from `data/`, tentative from"
        f" `data/stats.json` (generated {stats.get('generated_at', '?')[:10]}).",
        "",
        "| Tier | Records |",
        "|---|---:|",
        f"| trusted | {sum(trusted.values()):,} |",
        f"| staging | {sum(staging.values()):,} in {sum(1 for r in rows if r[2])} libraries |",
        f"| tentative (all libraries, per `stats.json`) | {sum(tentative.values()):,} |",
        "",
        f"Of the {len(rows)} registered libraries with a corpus the library can compile: {sum(1 for r in rows if r[1])} with trusted"
        f" records, {sum(1 for r in rows if r[2])} with translations in staging, {len(tentative_only)} tentative only, {len(empty)} without records.",
        "",
        "## Libraries with translations in staging or trusted",
        "",
        *table(sorted(translated, key=lambda r: (-r[1], -r[2], r[0]))),
        "",
        f"## Tentative only ({len(tentative_only)})",
        "",
        ", ".join(f"`{r[0]}`" for r in sorted(tentative_only, key=lambda r: -r[3])),
        "",
    ]
    text = "\n".join(out)
    if a.out:
        a.out.write_text(text, encoding="utf-8")
    else:
        print(text)


if __name__ == "__main__":
    main()
