#!/usr/bin/env python3
"""isnad_tag.py — write isnad tags into Lean files, take them out again, and check that nothing else changed (docs/isnad.md).

A tag is one line, the last line of a theorem's docstring:  @isnad1 id=… from=… src=… shape=… vocab=…
  - a theorem with a docstring gets the line before the docstring's closing `-/` (the closing moves to its own line if it followed text);
  - a theorem without one gets a new docstring holding only the tag:  /--\\n<tag>\\n-/\\n  (placed where the command starts: before its attributes);
  - a tag already there is replaced by the new one, or left alone when it is the same.

Where a theorem is written comes from Lean (`tengoku-isnad --ranges`: the command's range, docstring and attributes included, and the declared name's range). A theorem
whose text at the name's position is not its name was generated by a macro (`to_additive`'s twin points at the attribute that made it) and is skipped, with the reason;
two theorems at one command start (a `mutual` block, a macro generating several) are skipped too. The id of every theorem, tagged or not, goes in the module's list instead.

`equivalent(base, head)` is the law the tag PR class will rest on: after the tags and the docstrings the tagger created are taken out, the code is byte for byte what it was
and every docstring has the same words (whitespace at a docstring's end may differ: the closing `-/` of `text -/` moves to its own line, and pure insertion cannot
restore it, since `text-/` and `text\\n-/` would end up the same).
"""

from __future__ import annotations

import re
from dataclasses import dataclass

TAG_LINE = re.compile(r"^[ \t]*@isnad\d+ [\x21-\x7e ]*$")
TAG_IN_LINE = re.compile(r"@isnad\d+ ")


def skip_block_comment(text: str, i: int) -> int:
    """`i` is at `/-`; the index just after the matching `-/` (nested comments count), or len(text) when it is never closed."""
    depth, n = 0, len(text)
    while i < n:
        if text.startswith("/-", i):
            depth, i = depth + 1, i + 2
        elif text.startswith("-/", i):
            depth, i = depth - 1, i + 2
            if depth == 0:
                return i
        else:
            i += 1
    return n


def scan(text: str) -> list[tuple[str, int, int]]:
    """The text as segments (kind, start, end), kind in code / doc (a `/--` docstring) / comment (`/- -/`, `/-! -/`, `-- …`) / string: every byte in exactly one
    segment, so a docstring-like text inside a string or a comment is never taken for a docstring."""
    out, i, n, code_from = [], 0, len(text), 0

    def flush(upto: int) -> None:
        if upto > code_from:
            out.append(("code", code_from, upto))

    while i < n:
        c = text[i]
        if text.startswith("/-", i):
            flush(i)
            end = skip_block_comment(text, i)
            kind = "doc" if text.startswith("/--", i) and not text.startswith("/--/", i) else "comment"
            out.append((kind, i, end))
            i = code_from = end
        elif text.startswith("--", i):
            flush(i)
            end = text.find("\n", i)
            end = n if end < 0 else end
            out.append(("comment", i, end))
            i = code_from = end
        elif c == '"':
            flush(i)
            j = i + 1
            while j < n and text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            end = min(j + 1, n)
            out.append(("string", i, end))
            i = code_from = end
        else:
            i += 1
    flush(n)
    return out


def offset_of(text: str, line: int, col: int) -> int:
    """The index of (line from 1, column from 0 in code points): Python strings are sequences of code points, as Lean's columns are."""
    idx = 0
    for _ in range(line - 1):
        nl = text.find("\n", idx)
        if nl < 0:
            raise ValueError(f"no line {line}")
        idx = nl + 1
    return idx + col


@dataclass
class Item:
    """One theorem to tag: what Lean says about where it is written, and the tag line."""

    name: str
    rng: tuple[int, int, int, int]  # start line, start col, end line, end col of the whole command
    sel: tuple[int, int, int, int]  # the declared name
    tag: str


def declared_name_matches(name: str, written: str) -> bool:
    """The text at the name's position is the theorem's name, in full or as the last components (`theorem Foo.bar` inside `namespace X`, or `bar` inside it)."""
    return name == written or name.endswith("." + written)


def with_tag(doc: str, tag: str, indent: str = "") -> tuple[str, str]:
    """A docstring `/-- … -/` with the tag as its last line, and what happened: 'added', 'replaced' or 'same'. `indent` is the command's indentation: the tag and the
    closing, when the tagger puts them on lines of their own, are indented like it."""
    body = doc[3:-2]  # between `/--` and `-/`
    lines = body.split("\n")
    if len(lines) > 1 and lines[-1].strip() == "":
        # the closing `-/` stands on a line of its own, indented by lines[-1]: the tag is the line before it
        indent, before = lines[-1], lines[:-1]
        if before and TAG_LINE.match(before[-1]):
            if before[-1].strip() == tag:
                return doc, "same"
            return "/--" + "\n".join([*before[:-1], indent + tag, indent]) + "-/", "replaced"
        return "/--" + "\n".join([*before, indent + tag, indent]) + "-/", "added"
    if TAG_LINE.match(lines[-1].rstrip(" \t")) and lines[-1].strip() != "":
        # the last line of the docstring is a tag and the closing follows it on that line
        if lines[-1].strip() == tag:
            return doc, "same"
        lines[-1] = tag + lines[-1][len(lines[-1].rstrip(" \t")) :]
        return "/--" + "\n".join(lines) + "-/", "replaced"
    # the closing follows text: the tag goes on a line of its own, and the closing on another
    return "/--" + body.rstrip(" \t") + "\n" + indent + tag + "\n" + indent + "-/", "added"


def counts_zero() -> dict[str, int]:
    return {"added": 0, "replaced": 0, "same": 0, "created": 0}


def tag_text(text: str, items: list[Item]) -> tuple[str, dict[str, int], list[tuple[str, str]]]:
    """The text with every item's tag written, a count per outcome, and the (name, reason) of those skipped."""
    skipped: list[tuple[str, str]] = []
    counts = {"added": 0, "replaced": 0, "same": 0, "created": 0}
    if "\r" in text:
        return text, counts_zero(), [(it.name, "the file has CRLF line endings") for it in items]
    placed: list[tuple[int, Item]] = []
    starts: dict[int, list[Item]] = {}
    for it in items:
        try:
            p = offset_of(text, it.rng[0], it.rng[1])
            s0, s1 = offset_of(text, it.sel[0], it.sel[1]), offset_of(text, it.sel[2], it.sel[3])
        except ValueError as e:
            skipped.append((it.name, f"position outside the file ({e})"))
            continue
        if not declared_name_matches(it.name, text[s0:s1]):
            skipped.append((it.name, f"generated: the text at its name's position is {text[s0:s1]!r}"))
            continue
        starts.setdefault(p, []).append(it)
    for p, group in starts.items():
        if len(group) > 1:
            skipped += [(g.name, "several theorems start at one command (mutual, or generated together)") for g in group]
            continue
        placed.append((p, group[0]))
    for p, it in sorted(placed, key=lambda x: -x[0]):  # from the end: an edit never moves one still to do
        if text.startswith("/--", p) and not text.startswith("/--/", p):
            end = skip_block_comment(text, p)
            if not text.startswith("-/", end - 2):
                skipped.append((it.name, "its docstring is never closed"))
                continue
            line_start = text[text.rfind("\n", 0, p) + 1 : p]
            new, what = with_tag(text[p:end], it.tag, line_start if not line_start.strip() else "")
            counts[what] += 1
            text = text[:p] + new + text[end:]
        else:
            indent = text[text.rfind("\n", 0, p) + 1 : p]
            if indent.strip():  # something other than indentation before the command on its line
                skipped.append((it.name, "the command does not start its line"))
                continue
            counts["created"] += 1
            text = text[:p] + f"/--\n{indent}{it.tag}\n{indent}-/\n{indent}" + text[p:]
    return text, counts, skipped


def strip_text(text: str) -> str:
    """The text without any tag: tag lines are removed from the docstrings that have them. A docstring with no words left goes whole, with the line break and the
    indentation after it: that is what the tagger's own docstring (`/--\\n<tag>\\n-/`, made for a theorem that had none) looks like without its tag, and an empty
    docstring (`/-- -/`) the file had before is indistinguishable from it once tagged, so it goes too. Nothing is lost: it had no words."""
    out, last = [], 0
    for kind, a, b in scan(text):
        if kind != "doc":
            continue
        lines = text[a + 3 : b - 2].split("\n")
        kept = [ln for ln in lines if not TAG_LINE.match(ln)]
        blank = all(not ln.strip() for ln in kept)
        if len(kept) == len(lines) and not blank:
            continue
        out.append(text[last:a])
        if blank:
            indent = text[text.rfind("\n", 0, a) + 1 : a]
            tail = "\n" + indent
            last = b + len(tail) if indent.strip() == "" and text.startswith(tail, b) else b
        else:
            out.append("/--" + "\n".join(kept) + "-/")
            last = b
    out.append(text[last:])
    return "".join(out)


def normalise_doc_end(doc: str) -> str:
    return re.sub(r"[ \t\r\n]*-/$", "-/", doc)


def equivalent(base: str, head: str) -> bool:
    """`head` is `base` with tags written (a tag that `base` had may be a different one in `head`): after the tags are taken out of both, the code is the same bytes and
    every docstring the same words."""
    base, head = strip_text(base), strip_text(head)
    a, b = scan(base), scan(head)
    if [k for k, *_ in a] != [k for k, *_ in b]:
        return False
    for (kind, x0, x1), (_, y0, y1) in zip(a, b, strict=True):
        s, t = base[x0:x1], head[y0:y1]
        if kind == "doc":
            s, t = normalise_doc_end(s), normalise_doc_end(t)
        if s != t:
            return False
    return True
