/-
Copyright (c) 2024 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
import Tengoku
import Tengoku.Std
import Tengoku.Tactic.Aesop
import Tengoku.Meta.Qq

/-!
# SL_n(ℤ) is generated by transvections

Every element of `SL_n(ℤ)` can be written as a product of elementary
transvection matrices `E_{ij}(c) = I + c·e_{ij}`.

## Main results

* `SLnZ_transvec_gen` — every `σ ∈ SL_n(ℤ)` equals `L.prod` for a list `L`
  of transvections.
-/

/-- An elementary transvection in `SL_m(ℤ)`: the matrix `I + c·e_{ij}`. -/
def slTransvecG {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ) :
    Matrix.SpecialLinearGroup (Fin m) ℤ :=
  ⟨Matrix.transvection i j c, Matrix.det_transvection_of_ne i j hij c⟩

/-- A matrix in `SL_m(ℤ)` is a transvection if it equals `slTransvecG i j hij c`
for some `i ≠ j` and scalar `c`. -/
def IsTransvec {m : ℕ} (E : Matrix.SpecialLinearGroup (Fin m) ℤ) : Prop :=
  ∃ (i j : Fin m) (hij : i ≠ j) (c : ℤ), E = slTransvecG i j hij c

private def col0Sum {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) : ℕ :=
  ∑ i : Fin (m+1), (σ.1 i 0).natAbs

private def nzCount {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) : ℕ :=
  (Finset.univ.filter fun i : Fin (m+1) ↦ σ.1 i 0 ≠ 0).card

private def blockLift {m : ℕ} (i j : Fin m) (hij : i ≠ j) (c : ℤ) :
    Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ :=
  slTransvecG i.succ j.succ (fun h ↦ hij (Fin.succ_injective m h)) c

private lemma det_lowerRight {m : ℕ} (τ : Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (h0j : ∀ j : Fin (m + 1), j ≠ 0 → τ.1 0 j = 0) :
    (Matrix.of fun (i : Fin m) (j : Fin m) ↦ τ.1 i.succ j.succ).det = 1 := by
  change (τ.1.submatrix Fin.succ Fin.succ).det = 1
  have hdet : τ.1.det = 1 := τ.2
  rw [Matrix.det_succ_row_zero, Finset.sum_eq_single (0 : Fin (m + 1))
    (fun j _ hj ↦ by simp [h0j j hj])
    (fun h ↦ absurd (Finset.mem_univ _) h)] at hdet
  simpa [Fin.succAbove_zero, h00] using hdet

private def extractBlock {m : ℕ} (τ : Matrix.SpecialLinearGroup (Fin (m + 1)) ℤ)
    (h00 : τ.1 0 0 = 1) (h0j : ∀ j : Fin (m + 1), j ≠ 0 → τ.1 0 j = 0)
    (_hi0 : ∀ i : Fin (m + 1), i ≠ 0 → τ.1 i 0 = 0) :
    Matrix.SpecialLinearGroup (Fin m) ℤ :=
  ⟨Matrix.of fun i j ↦ τ.1 i.succ j.succ, det_lowerRight τ h00 h0j⟩

private def row0Sum {m : ℕ} (σ : Matrix.SpecialLinearGroup (Fin (m+1)) ℤ) : ℕ :=
  ∑ j : Fin (m+1), if (j : ℕ) = 0 then 0 else (σ.1 0 j).natAbs
