import Tengoku.Flt.FLT.AutomorphicForm.GroupTheoryStuff
import Tengoku.Flt.FLT.AutomorphicForm.QuaternionAlgebra.HeckeOperators.Abstract
import Tengoku.Flt.FLT.AutomorphicForm.Stuff
import Tengoku.Flt.FLT.Basic.Lemmas
import Tengoku.Flt.FLT.DedekindDomain.FiniteAdeleRing.IsDirectLimitRestricted
import Tengoku.Flt.FLT.DedekindDomain.FiniteAdeleRing.TensorPi
import Tengoku.Flt.FLT.Deformations.Algebra.InverseLimit.Basic
import Tengoku.Flt.FLT.Deformations.Algebra.InverseLimit.Topology
import Tengoku.Flt.FLT.Deformations.ContinuousRepresentation.IsTopologicalModule
import Tengoku.Flt.FLT.Deformations.RepresentationTheory.Frobenius
import Tengoku.Flt.FLT.Deformations.Subfunctor
import Tengoku.Flt.FLT.FreyCurve.Basic
import Tengoku.Flt.FLT.FreyCurve.FreyPackage
import Tengoku.Flt.FLT.HaarMeasure.MeasurableSpacePadics
import Tengoku.Flt.FLT.HenselianLocalRing.Stuff
import Tengoku.Flt.FLT.KnownIn1980s.EllipticCurves.QuadraticTwists.QuadraticTwists
import Tengoku.Flt.FLT.KnownIn1980s.EllipticCurves.QuadraticTwists.SplitMultiplicativeReduction
import Tengoku.Flt.FLT.KnownIn1980s.EllipticCurves.ReductionBaseChange
import Tengoku.Flt.FLT.KnownIn1980s.EllipticCurves.TateCurveBaseChange
import Tengoku.Flt.FLT.KnownIn1980s.EllipticCurves.TateParameter
import Tengoku.Flt.FLT.KnownIn1980s.PGL2.Defs
import Tengoku.Flt.FLT.KnownIn1980s.RepresentationTheory.OddAbsIrred
import Tengoku.Flt.FLT.Mathlib.Algebra.Algebra.Equiv
import Tengoku.Flt.FLT.Mathlib.Algebra.Algebra.Tower
import Tengoku.Flt.FLT.Mathlib.Algebra.Central.TensorProduct
import Tengoku.Flt.FLT.Mathlib.Algebra.Group.Action.Hom
import Tengoku.Flt.FLT.Mathlib.Algebra.Homology.HomologicalComplex
import Tengoku.Flt.FLT.Mathlib.Algebra.IsDirectLimit
import Tengoku.Flt.FLT.Mathlib.Algebra.IsQuaternionAlgebra
import Tengoku.Flt.FLT.Mathlib.Algebra.Module.Submodule.Basic
import Tengoku.Flt.FLT.Mathlib.Algebra.Module.TransferInstance
import Tengoku.Flt.FLT.Mathlib.Algebra.Order.AbsoluteValue.Basic
import Tengoku.Flt.FLT.Mathlib.Algebra.Polynomial.QuadraticDiscriminant
import Tengoku.Flt.FLT.Mathlib.Algebra.Polynomial.Splits
import Tengoku.Flt.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Tengoku.Flt.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.Aut
import Tengoku.Flt.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.GaloisDescent
import Tengoku.Flt.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.Reduction
import Tengoku.Flt.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.VariableChange
import Tengoku.Flt.FLT.Mathlib.AlgebraicGeometry.EllipticCurve.Weierstrass
import Tengoku.Flt.FLT.Mathlib.Data.Fin.Basic
import Tengoku.Flt.FLT.Mathlib.Data.Real.Archimedean
import Tengoku.Flt.FLT.Mathlib.Data.Set.Prod
import Tengoku.Flt.FLT.Mathlib.FieldTheory.Galois.Basic
import Tengoku.Flt.FLT.Mathlib.FieldTheory.Separable
import Tengoku.Flt.FLT.Mathlib.FieldTheory.SeparableDegree
import Tengoku.Flt.FLT.Mathlib.FieldTheory.SplittingField.IsSplittingField
import Tengoku.Flt.FLT.Mathlib.GroupTheory.GroupAction.Quotient
import Tengoku.Flt.FLT.Mathlib.GroupTheory.SpecificGroups.Cyclic
import Tengoku.Flt.FLT.Mathlib.LinearAlgebra.Countable
import Tengoku.Flt.FLT.Mathlib.LinearAlgebra.Dimension.Constructions
import Tengoku.Flt.FLT.Mathlib.LinearAlgebra.Dimension.IsQuadraticExtension
import Tengoku.Flt.FLT.Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import Tengoku.Flt.FLT.Mathlib.LinearAlgebra.Matrix.Transvection
import Tengoku.Flt.FLT.Mathlib.LinearAlgebra.Pi
import Tengoku.Flt.FLT.Mathlib.LinearAlgebra.TensorProduct.Algebra
import Tengoku.Flt.FLT.Mathlib.LinearAlgebra.TensorProduct.FiniteFree
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.AdicCompletion
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.FiniteAdeleRing
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.InfinitePlace
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Constructions.BorelSpace.RestrictedProduct
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Group.Action
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Group.Measure
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Haar.Extension
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Measure.Regular
import Tengoku.Flt.FLT.Mathlib.MeasureTheory.Measure.Typeclasses.Finite
import Tengoku.Flt.FLT.Mathlib.NumberTheory.NumberField.InfinitePlace.Basic
import Tengoku.Flt.FLT.Mathlib.NumberTheory.NumberField.InfinitePlace.Completion
import Tengoku.Flt.FLT.Mathlib.NumberTheory.Padics.PadicIntegers
import Tengoku.Flt.FLT.Mathlib.Order.Filter.Cofinite
import Tengoku.Flt.FLT.Mathlib.RingTheory.AdjoinRoot
import Tengoku.Flt.FLT.Mathlib.RingTheory.DedekindDomain.AdicValuation
import Tengoku.Flt.FLT.Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
import Tengoku.Flt.FLT.Mathlib.RingTheory.DiscreteValuationRing.AdjoinRoot
import Tengoku.Flt.FLT.Mathlib.RingTheory.DiscreteValuationRing.Separable
import Tengoku.Flt.FLT.Mathlib.RingTheory.Ideal.Quotient.Basic
import Tengoku.Flt.FLT.Mathlib.RingTheory.LocalRing.Defs
import Tengoku.Flt.FLT.Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import Tengoku.Flt.FLT.Mathlib.RingTheory.Localization.BaseChange
import Tengoku.Flt.FLT.Mathlib.RingTheory.Norm.Quadratic
import Tengoku.Flt.FLT.Mathlib.RingTheory.Norm.Quotient
import Tengoku.Flt.FLT.Mathlib.RingTheory.Polynomial.GaussLemma
import Tengoku.Flt.FLT.Mathlib.RingTheory.RamificationInertia.Basic
import Tengoku.Flt.FLT.Mathlib.RingTheory.SimpleRing.TensorProduct
import Tengoku.Flt.FLT.Mathlib.RingTheory.TensorProduct.Pi
import Tengoku.Flt.FLT.Mathlib.RingTheory.Unramified.LocalRing
import Tengoku.Flt.FLT.Mathlib.RingTheory.Valuation.Discrete.IsDiscreteValuationRing
import Tengoku.Flt.FLT.Mathlib.RingTheory.Valuation.ValuationSubring
import Tengoku.Flt.FLT.Mathlib.RingTheory.Valuation.ValuativeRel.Basic
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.ContinuousAlgEquiv
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.ContinuousMonoidHom
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.ContinuousSMulDiscrete
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Group.Basic
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Group.Quotient
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Group.Units
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Module.Equiv
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Module.FiniteDimension
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Module.Quotient
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Module.TensorProduct
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Monoid
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.MulAction
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Order.Field
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.RestrictedProduct.Basic
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.ValuativeRel.ValuativeTopology
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Valued.ValuationTopology
import Tengoku.Flt.FLT.Mathlib.Topology.Algebra.Valued.WithZeroMulInt
import Tengoku.Flt.FLT.Mathlib.Topology.Bases
import Tengoku.Flt.FLT.Mathlib.Topology.CompactOpen
import Tengoku.Flt.FLT.Mathlib.Topology.HomToDiscrete
import Tengoku.Flt.FLT.Mathlib.Topology.MetricSpace.ProperSpace.InfinitePlace
import Tengoku.Flt.FLT.Mathlib.Topology.Polish
import Tengoku.Flt.FLT.NumberField.DiscriminantBounds
import Tengoku.Flt.FLT.NumberField.InfinitePlace.Extension
import Tengoku.Flt.FLT.NumberField.Padics.RestrictedProduct
import Tengoku.Flt.FLT.Patching.Utils.AdicTopology
import Tengoku.Flt.FLT.Patching.Utils.Depth
import Tengoku.Flt.FLT.Patching.Utils.InverseLimit
import Tengoku.Flt.FLT.Patching.Utils.Lemmas
import Tengoku.Flt.FLT.Patching.Utils.TopologicallyFG
import Tengoku.Flt.FLT.Slop.DimensionTheorem.Numeric
import Tengoku.Flt.FLT.Slop.NumberTheory.TsumDivisorsAntidiagonal
import Tengoku.Flt.FLT.Slop.RepresentationTheory.OddAbsIrredOrig
import Tengoku.Flt.FLT.Slop.RepresentationTheory.OddAbsIrredSlop
